name: Build and Push to ACR

on:
  push:
    branches:
      - main

env:
  REGISTRY: studenterpcicd.azurecr.io
  IMAGE_NAME: student-erp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name studenterpcicd

      - name: Build Docker image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
